### ISSUE TITLE
confused about elasticsearch logs

### ISSUE THREAD

**Issue by crooy** [astronomer/airflow-chart#118]
Hi,

i have a nicely working airflow cluster using your chart, its running in GKE, in the same namespace i run the Elasticsearch helm chart from elastic. Both work nicely, and can talk to each other.

This is the relevant yaml part

```
elasticsearch:
    enabled: true
    connection:
        host: elasticsearch-master
        port: 9200
```

But i dont see the logs, could you point me to what i am doing wrong?

**Comment by schnie** [comment]
Hey @crooy sorry for the super late reply here. If this is still relevant to you, what version of Airflow are you running? Older versions of Airflow didn't populate the `log_id` of the log records, so we use fluentd to add that field. For example - https://github.com/astronomer/astronomer/blob/master/charts/fluentd/templates/fluentd-configmap.yaml#L163-L171.

This has since been fixed inside Airflow I believe, meaning this shouldn't be needed anymore.

**Comment by crooy** [comment]
Hi,

so i have the basic airflow setup running smoothly, with our DAGs, I have an elasisticsearch. Its not very well documented, but it appears i need fluentd to move the logs from the task-pods (we use the kubernetes-executor) to elasticsearch.

Now if i try to deploy the astronomer/fluentd chart i get this error

`helm install fluentd --set elasticsearch.host=elasticsearch-master astronomer/fluentd`

```
Error: template: fluentd/templates/fluentd-serviceaccount.yaml:4:14: executing "fluentd/templates/fluentd-serviceaccount.yaml" at <.Values.global.rbacEnabled>: nil pointer evaluating interface {}.rbacEnabled
````

**Comment by crooy** [comment]
Ok,
I realized i can set config keys using Env vars also so this is almost fixing it for me:
` 
 - name: AIRFLOW__CORE__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER
    value: "gs://xxxxxx"
  - name: AIRFLOW__CORE__REMOTE_LOG_CONN_ID
    value: "google_cloud_default"
`

I see the logs in the gcs bucket, but i get this error in the UI

`

*** Unable to fetch logs from worker pod  ***
(403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'xxxxxxx', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 29 Oct 2020 10:14:55 GMT', 'Content-Length': '311'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \\"system:serviceaccount:default:airflow-webserver-serviceaccount\\" cannot list resource \\"pods/log\\" in API group \\"\\" in the namespace \\"default\\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}\n'

`

**Comment by crooy** [comment]
ok i figured this one out, its possible i missed this error and it was the same problem with elastic search 🤔 

i fixed this one with this, i think its actually missing the chart:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: airflow-pod-viewer-role
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-pod-viewer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-pod-viewer-role
subjects:
  - kind: ServiceAccount
    name: airflow-webserver-serviceaccount
    namespace: default

```
