### ISSUE TITLE
Airflow with secret(k8s secret object) doesnot work 

### ISSUE THREAD

**Issue by saikatharryc** [astronomer/airflow-chart#169]
I have used the secret field in value like this:

```
secret:
  - envName: BH_DB_HOST
    secretName: airflow-secrets
    secretKey: BH_DB_HOST
  - envName: BH_DB_NAME
    secretName: airflow-secrets
    secretKey: BH_DB_NAME
```
I'm using this: https://github.com/astronomer/ap-airflow/tree/master/1.10.10

and it gives me this kind of error in the scheduler, 
any idea of this?

<img width="1258" alt="Screen Shot 2020-12-05 at 9 42 25 PM" src="https://user-images.githubusercontent.com/15653282/101248609-0029ad80-3743-11eb-8351-51b199b6eebe.png">
