### ISSUE TITLE
configmap sourced env values

### ISSUE THREAD

**Issue by EliMor** [astronomer/airflow-chart#220]
Chart assumes clients will only want to add environment variables as name/values. 
Client won't be able to do something like

```
- name: ENV_VAR
   valueFrom:
       configMapKeyRef:
           name: configmap-name
           key: configmap-field
```
