### ISSUE TITLE
Syncing dags from multiple git-repos

### ISSUE THREAD

**Issue by somasays** [astronomer/airflow-chart#241]
Is it possible to sync from several repositories into the dags foder using git-sync, example below. The intention being, to have a sort of multi-tenent aiflow cluster, where dags can be deployed from several git repositories

```yaml
extraContainers:
    - name: gitsync-repo-1
      image: k8s.gcr.io/git-sync/git-sync:v3.2.2
      imagePullPolicy: IfNotPresent
      env:
        - name: GIT_SYNC_REPO
          value: https://github.com/company/repo-1.git
        - name: GIT_SYNC_ROOT
          ......
      volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: dags
          readOnly: false
      extraVolumeMounts:
        - name: dags
          mountPath: /usr/local/airflow/dags
      extraVolumes:
        - name: dags
          emptyDir: {}

    - name: gitsync-repo-2
      image: k8s.gcr.io/git-sync/git-sync:v3.2.2
      imagePullPolicy: IfNotPresent
      env:
        - name: GIT_SYNC_REPO
          value: https://github.com/company/repo-2.git
        - name: GIT_SYNC_ROOT
          ......
      volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: dags
          readOnly: false
      extraVolumeMounts:
        - name: dags
          mountPath: /usr/local/airflow/dags
      extraVolumes:
        - name: dags
          emptyDir: {}
```
