### ISSUE TITLE
Help needed - additionalVolume not parsable by helm with version 0.25.8

### ISSUE THREAD

**Issue by xwing3** [astronomer/airflow-chart#254]
Hello,
Astronomer helm chart version: 0.25.8

```
////// Config
astronomer:
  astroUI:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1024Mi"
  houston:
    resources:
      requests:
        cpu: "500m"
        memory: "1024Mi"
      limits:
        cpu: "1000m"
        memory: "2048Mi"
    config:
      executor: "CeleryExecutor"
      publicSignups: true
      email:
        enabled: true
        reply: "astronomer@dsd.net"
      deployments:
        helm:
          workers:
            additionalVolume:
              enabled: true
              capacity: 100Gi
              storageClassName: "efs"
              mountPath: "/data"
              volumePlugin: {}
```

And I get the following error in houston pod logs:
`
astronomer-houston-upgrade-deployments-b7wk7 post-upgrade-job 2021-10-13T17:58:25 INFO Response from #updateDeployment: {"result":{"message":"YAML parse error on airflow/templates/workers/worker-persistentvolume.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key"},"deployment":{}}
`

https://github.com/astronomer/airflow-chart/blob/v0.20.1/templates/workers/worker-persistentvolume.yaml -> this is the template that throws the error. Am I doing something wrong or is the template the problem?
