### ISSUE TITLE
Log Grooming script envvars

### ISSUE THREAD

**Issue by skiedude** [astronomer/airflow-chart#450]
```
    scheduler:
      logGroomerSidecar:
        enabled: True
        retentionDays: 7
        args: ["/usr/local/bin/clean-airflow-logs"]
```
Setting the following I would expect the logGroomer to clean the logs of anything older than 7 days. 

This translates to setting an envvar in the sidecar of `AIRFLOW__LOG_RETENTION_DAYS`, however in `/usr/local/bin/clean-airflow-logs` its looking for `RETENTION=${ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION_DAYS:-15}`

Is there a setting I'm missing to create the astronomer envvar for the logGroomerSidecar?
