### ISSUE TITLE
Task logs not found in Web-UI

### ISSUE THREAD

**Issue by otosky** [astronomer/airflow-chart#46]
This might be a simple fix, but what should I alter in the chart/templates to be able to access the task logs in the Airflow Web UI?

Currently using the default KubernetesExecutor and getting a "Log file does not exist:" error.  Also not seeing a Persistent Volume Claims for the workers?

**Comment by schnie** [comment]
Hey @otosky, If you use the `KubernetesExecutor`, you'll need to also configure a logging system, since those pods are ephemeral, Airflow can't rely on them being around.

We typically deploy with an Elasticsearch cluster for `KubernetesExecutor` logs and enable that feature in the `values.yaml` here.

You could also set the appropriate environment variables to enable S3 or GCS logs as a possible simpler fix.

If you aren't tied to the `KubernetesExecutor`, you could also override that `executor` configuration to be `CeleryExecutor`, which would deploy static celery workers that use a `StatefulSet` to write logs to the workers by default.

`LocalExecutor` setting would also work, as the log files just get written to the scheduler pod.

cc @dimberman

**Comment by otosky** [comment]
@schnie - got it!  I hadn't noticed that there wasn't an Elasticsearch template in the `templates` directory, so I was similarly confused when enabling that feature resulted in an error.

Using GCS now and it's working great!

Closing the issue.

**Comment by eduardchai** [comment]
Hey @otosky, do you mind sharing your gcs configuration? I did not manage to find the configurations in this repo. Thank you!

**Comment by otosky** [comment]
@eduardchai sure thing - this is the relevant portion of my edited `templates/configmap.yaml`, it's really just the addition of the last three lines to enable the GCS logging, where the conn_id 'gcs' was added after deployment.

```yaml
################################
## Airflow ConfigMap
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "airflow_config" . }}
  labels:
    tier: airflow
    component: config
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
data:
  # These are system-specified config overrides.
  airflow.cfg: |
    [core]
    load_examples = False
    colored_console_log = False
    executor = {{ .Values.executor }}
{{- if .Values.elasticsearch.enabled }}
    remote_logging = True
{{- end }}
    remote_logging = True
    remote_base_log_folder = gs://YOUR-BUCKET_HERE
    remote_log_conn_id = gcs
```

Note: I haven't pulled and updated my copy of the repo in a while, so apologies if any of the settings are out of sync with the current HEAD...
